# Generated by Django 4.1.1 on 2022-10-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_review_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='display',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=200, null=True),
        ),
    ]
