# Generated by Django 4.1.1 on 2022-10-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_review_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pancard',
            field=models.ImageField(default='images/profile.png', upload_to='pancard/'),
        ),
    ]
