# Generated by Django 4.1.1 on 2022-10-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_userprofile_pancard'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateTimeField()),
                ('star_client_image', models.ImageField(default='images/profile.png', upload_to='pastevents/')),
                ('star_client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client1_image', models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='pastevents/')),
                ('client2_image', models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='pastevents/')),
                ('client3_image', models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='pastevents/')),
                ('client4_image', models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='pastevents/')),
                ('client5_image', models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='pastevents/')),
                ('client6_image', models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='pastevents/')),
                ('client7_image', models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='pastevents/')),
                ('client8_image', models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='pastevents/')),
                ('client9_image', models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='pastevents/')),
                ('client10_image', models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='pastevents/')),
                ('client1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client4_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client5_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client6_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client7_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client8_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client9_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client10_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
