# Generated by Django 4.1.1 on 2022-10-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_pastevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastevent',
            name='client10_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastevents/'),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='client1_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastevents/'),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='client2_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastevents/'),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='client3_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastevents/'),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='client4_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastevents/'),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='client5_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastevents/'),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='client6_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastevents/'),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='client7_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastevents/'),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='client8_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastevents/'),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='client9_image',
            field=models.ImageField(blank=True, null=True, upload_to='pastevents/'),
        ),
    ]
